openapi: "3.0.2"
info:
  title: InTheGame API
  description: Your favorite teams all in one place
  version: "1.0"
servers:
  - url: https://api.inthegame.test/v1
paths:
  /auth:
    post:
      responses:
        "201":
          description: create user session (login)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
    delete:
      responses:
        "204":
          description: remove user session (logout)
          content:
            application/json:
              schema:
                type: string
  /teams:
    get:
      responses:
        "200":
          description: List of all available teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Team"
  /users/{userid}/subscriptions:
    put:
      requestBody:
        description:
      responses:
        "200":
          description: Update subscription settings (i.e. add teams or change notification settings)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subscription"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
